# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SecondLook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SecondLook
  pod 'TensorFlowLiteSwift'

  target 'SecondLookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SecondLookUITests' do
    # Pods for testing
  end

end
