# -*- coding: utf-8 -*-
"""second_look_augmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_XAE3n6qqmVjBe829Nh7qiTBmtcLGF0I
"""

# Install dependencies to ensure the environment has lightweight, headless image-processing
# tools (needed in Colab where GUI-based OpenCV is not supported)
!pip install opencv-python-headless pillow numpy matplotlib -q

import cv2, os, random
import numpy as np
from PIL import Image, ImageEnhance
import matplotlib.pyplot as plt
from google.colab import files

# Fix randomness so results remain consistent across runs (important for debugging and comparison)
random.seed(42)
np.random.seed(42)

# Create a dedicated directory to avoid clutter and ensure all images are stored in one place
os.makedirs('/content/sample_images', exist_ok=True)

# Use Colab’s upload interface since local file paths are not directly accessible in this environment
uploaded = files.upload()

for i, fname in enumerate(uploaded.keys()):
    # Preserve file extension to avoid compatibility issues during later image processing
    ext = os.path.splitext(fname)[1]

    # Standardize filenames to simplify downstream processing (avoids issues with spaces/special characters)
    new_name = f'/content/sample_images/img_{i}{ext}'

    # Save files explicitly to control file structure and ensure consistent access paths later
    with open(new_name, 'wb') as f:
        f.write(uploaded[fname])

# Print filenames to verify successful upload and renaming before proceeding further
print('Uploaded:', os.listdir('/content/sample_images'))

import cv2
import numpy as np
import random
from PIL import Image, ImageEnhance

# Fix randomness so augmentation behavior is reproducible across runs
random.seed(42)
np.random.seed(42)

def add_glare(img, mask=None):
    # Glare affects only intensity, so segmentation masks remain valid
    out = img.copy().astype(np.float32)
    h, w = out.shape[:2]
    cx, cy = random.randint(w//4, 3*w//4), random.randint(h//4, 3*h//4)
    rx, ry = random.randint(w//10, w//4), random.randint(h//10, h//4)
    glare_mask = np.zeros((h, w), dtype=np.float32)
    cv2.ellipse(glare_mask, (cx,cy), (rx,ry), 0, 0, 360, 1.0, -1)
    glare_mask = cv2.GaussianBlur(glare_mask, (0,0), sigmaX=max(rx//2, 1))

    # Scale glare based on brightness so darker images are not overexposed
    intensity = 0.3 + (0.3 * (np.mean(out) / 255.0))
    out += glare_mask * 255 * intensity

    out = np.clip(out, 0, 255).astype(np.uint8)
    return (out, mask) if mask is not None else out

def add_motion_blur(img, mask=None):
    # Simulates real motion artifacts without shifting object positions
    size = 15
    angle = random.uniform(0, 180)
    kernel = np.zeros((size, size))
    kernel[size//2, :] = 1.0 / size
    M = cv2.getRotationMatrix2D((size//2, size//2), angle, 1)
    kernel = cv2.warpAffine(kernel, M, (size, size))
    s = kernel.sum()
    if s > 0:
        kernel /= s
    out = cv2.filter2D(img, -1, kernel)
    return (out, mask) if mask is not None else out

def add_compression(img, mask=None):
    # Mimics real-world quality loss from storage/transmission pipelines
    quality = random.randint(10, 35)
    ok, enc = cv2.imencode('.jpg', img, [cv2.IMWRITE_JPEG_QUALITY, quality])
    if not ok:
        return (img.copy(), mask) if mask is not None else img.copy()
    out = cv2.imdecode(enc, cv2.IMREAD_GRAYSCALE)
    return (out, mask) if mask is not None else out

def add_moire(img, mask=None):
    # Adds frequency-based noise pattern seen in scanning/display artifacts
    h, w = img.shape[:2]
    X, Y = np.meshgrid(np.arange(w), np.arange(h))
    wave = np.sin(2 * np.pi * 0.08 * (X * np.cos(0.5) + Y * np.sin(0.5)))
    wave = ((wave + 1) / 2 * 25).astype(np.float32)
    out = np.clip(img.astype(np.float32) + wave, 0, 255).astype(np.uint8)
    return (out, mask) if mask is not None else out

def add_brightness(img, mask=None):
    # Tests robustness under poor exposure (common in medical imaging)
    factor = random.uniform(0.25, 0.65)
    out = np.array(ImageEnhance.Brightness(Image.fromarray(img)).enhance(factor)).astype(np.uint8)
    return (out, mask) if mask is not None else out

def add_contrast(img, mask=None):
    # Makes subtle structures harder to detect to stress-test models
    factor = random.uniform(0.25, 0.60)
    out = np.array(ImageEnhance.Contrast(Image.fromarray(img)).enhance(factor)).astype(np.uint8)
    return (out, mask) if mask is not None else out

def add_occlusion(img, mask=None):
    # Simulates partial visibility while keeping labels usable
    out = img.copy().astype(np.float32)
    h, w = out.shape[:2]
    occ_mask = np.zeros((h, w), dtype=np.float32)
    rx, ry = random.randint(w//6, w//3), random.randint(h//8, h//5)
    cx, cy = random.randint(0, rx), random.randint(0, ry)
    cv2.ellipse(occ_mask, (cx,cy), (rx,ry), 0, 0, 360, 1.0, -1)
    occ_mask = cv2.GaussianBlur(occ_mask, (0,0), sigmaX=20)
    out = np.clip(out * (1 - occ_mask), 0, 255).astype(np.uint8)
    return (out, mask) if mask is not None else out

def add_perspective(img, mask=None):
    # Must apply identical transform to maintain image–mask alignment
    h, w = img.shape[:2]
    j = int(min(h,w)*0.08)
    src = np.float32([[0,0],[w,0],[w,h],[0,h]])
    dst = np.float32([
        [random.randint(0,j),   random.randint(0,j)],
        [w-random.randint(0,j), random.randint(0,j)],
        [w-random.randint(0,j), h-random.randint(0,j)],
        [random.randint(0,j),   h-random.randint(0,j)],
    ])
    M = cv2.getPerspectiveTransform(src, dst)
    out = cv2.warpPerspective(img, M, (w,h), borderMode=cv2.BORDER_REPLICATE)
    if mask is not None:
        mask_out = cv2.warpPerspective(mask, M, (w,h), borderMode=cv2.BORDER_REPLICATE)
        return out, mask_out
    return out

def add_rotation(img, mask=None):
    # Keeps annotation consistent by rotating image and mask together
    h, w = img.shape[:2]
    angle = random.uniform(-15, 15)
    M = cv2.getRotationMatrix2D((w//2, h//2), angle, 1)
    out = cv2.warpAffine(img, M, (w, h), borderMode=cv2.BORDER_REPLICATE)
    if mask is not None:
        mask_out = cv2.warpAffine(mask, M, (w, h), borderMode=cv2.BORDER_REPLICATE)
        return out, mask_out
    return out

def normalize(img):
    # Enforces a consistent format to prevent downstream pipeline errors
    if img.ndim == 3:
        img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    return np.clip(img, 0, 255).astype(np.uint8)

# Central registry simplifies random selection and extensibility
AUGMENTATIONS = {
    'glare': add_glare, 'motion_blur': add_motion_blur,
    'compression': add_compression, 'moire': add_moire,
    'brightness': add_brightness, 'contrast': add_contrast,
    'occlusion': add_occlusion, 'perspective': add_perspective,
    'rotation': add_rotation,
}

def quality_gate(img):
    # Filters out unrealistic samples based on empirically observed thresholds
    gray = img if img.ndim == 2 else cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    issues = 0
    if cv2.Laplacian(gray, cv2.CV_64F).var() < 8:
        issues += 1
    if np.mean(gray) < 20:
        issues += 1
    if np.mean(gray) > 240:
        issues += 1
    if np.mean(gray < 15) > 0.75:
        issues += 1
    return 'USABLE' if issues == 0 else ('BORDERLINE' if issues == 1 else 'UNUSABLE')

def apply_random_combo(img, mask=None):
    # Limited stacking preserves realism while increasing variability
    selected = random.sample(list(AUGMENTATIONS.items()), k=random.randint(1, 3))
    out = img.copy()
    out_mask = mask
    names = []
    for name, fn in selected:
        result = fn(out, out_mask)
        if isinstance(result, tuple):
            out, out_mask = result
        else:
            out = result
        out = normalize(out)
        names.append(name)
    if mask is not None:
        return out, out_mask, '+'.join(names)
    return out, '+'.join(names)

print('augmentations ready')

def show_grid(img_path):
    # Mammograms are single-channel, so grayscale avoids unnecessary processing
    img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
    if img is None:
        raise FileNotFoundError(f'could not load: {img_path}')

    h, w = img.shape
    # Resize only for visualization so multiple outputs can be compared clearly
    display_size = (int(w * 250/h), 250)

    all_images = {'original': cv2.resize(img, display_size)}
    all_labels = {'original': 'USABLE'}

    for name, fn in AUGMENTATIONS.items():
        # Skip mask handling to keep outputs simple for visual inspection
        result = fn(img.copy())
        aug = normalize(result if not isinstance(result, tuple) else result[0])
        all_images[name] = cv2.resize(aug, display_size)
        all_labels[name] = quality_gate(aug)

    # Random combos reveal whether stacked augmentations remain realistic
    for i in range(3):
        combo, combo_name = apply_random_combo(img)
        all_images[f'combo_{i+1}'] = cv2.resize(combo, display_size)
        all_labels[f'combo_{i+1}'] = f'{quality_gate(combo)}\n({combo_name})'

    # 3 columns avoids awkward empty spaces given total number of images
    cols, n = 3, len(all_images)
    rows = (n + cols - 1) // cols
    fig, axes = plt.subplots(rows, cols, figsize=(22, rows*6))
    axes = axes.flatten()

    for i, (name, im) in enumerate(all_images.items()):
        label = all_labels[name]
        # Color highlights help quickly identify problematic augmentations
        color = 'green' if 'USABLE' in label and 'BORDERLINE' not in label else ('orange' if 'BORDERLINE' in label else 'red')
        axes[i].imshow(im, cmap='gray')
        axes[i].set_title(f'{name}\n{label}', fontsize=9, color=color, fontweight='bold')
        axes[i].axis('off')

    # Hide unused axes so the grid remains visually clean
    for j in range(i+1, len(axes)):
        axes[j].axis('off')

    fname = os.path.basename(img_path)
    plt.suptitle(f'Second Look - Augmentation Grid | {fname}', fontsize=12, fontweight='bold')
    plt.tight_layout()
    plt.savefig(f'/content/{fname}_grid.png', dpi=150, bbox_inches='tight')
    plt.show()
    print(f'saved: {fname}_grid.png\n')

# Sorting ensures consistent output order for easier comparison across runs
for f in sorted(os.listdir('/content/sample_images')):
    if f.endswith('.png') or f.endswith('.jpg'):
        show_grid(f'/content/sample_images/{f}')

print('all done!')

import zipfile, os
from google.colab import files

# Exporting as a .py file allows the pipeline to be reused outside Colab (cleaner than sharing notebooks)
code = open('/content/augmentation.py', 'w')
code.write('''# Second Look - Augmentation Module
# Run: python augmentation.py
# Requires: opencv-python, pillow, numpy
# See notebook for full pipeline with grid visualization
''')
code.close()

# Packaging everything into one zip avoids dependency on Colab and simplifies sharing with the team
zip_path = '/content/second_look_augmentation.zip'

with zipfile.ZipFile(zip_path, 'w') as zipf:
    # Including the script ensures others can directly run or modify the augmentation logic
    zipf.write('/content/augmentation.py', 'augmentation.py')
    print('added: augmentation.py')

    # Original images are included for reference so augmentations can be validated visually
    for f in sorted(os.listdir('/content/sample_images/')):
        if f.endswith('.png') or f.endswith('.jpg'):
            zipf.write(f'/content/sample_images/{f}', f'originals/{f}')
            print(f'added original: {f}')

    # Grid outputs are included to save time, so reviewers don’t need to rerun the pipeline
    for f in sorted(os.listdir('/content/')):
        if f.endswith('_grid.png'):
            zipf.write(f'/content/{f}', f'grids/{f}')
            print(f'added grid: {f}')

print(f'\nall done - downloading zip...')
files.download(zip_path)